cosmos:
  api: mongo  # mongo | sql
  database: nlp-member-pco
  uri: "mongodb://cosmosuser:pass@host:10255/?ssl=true&retrywrites=false"

mongodb:
  uri: "mongodb://localhost:27017"
  database: nlp-member-pco

collections: {}

collection_defaults:
  enabled: true
  business_key: _id
  exclude_fields:
    - _etag
    - _ts

sampling:
  percentage: 5
  seed: 42

logging:
  main_log: "compare_summary.log"
  output_dir: "mismatch_logs"
